apiVersion: v1
kind: Service
metadata:
  name: {{ include "microsvc.fullname" . }}
  labels:
    {{- include "microsvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ include "microsvc.fullname" . }}.default.svc.cluster.local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microsvc.selectorLabels" . | nindent 4 }}
